### ISSUE TITLE
Checkout suddenly much slower on windows environment

### ISSUE THREAD

**Issue by yeu-degroot** [actions/checkout#1186]
> Moved from <https://github.com/actions/runner-images/issues/7180>

### Description

Since a few days, the duration of the `actions/checkout@v3` steps on `windows-2019` have dramatically increased.
This behavior is seen on all my repos (all private). Below a table showing an example of before/after.

| Checkout step | Feb 17th | Feb 21st |
| -- | -- | -- |
| 1 | `13s` | `1m35s` |
| 2 | `8s` | `47s` |

The result is a huge increase in build (and billable) time.

![image](https://user-images.githubusercontent.com/52652923/220855259-79a6e246-acd8-40b8-a9f3-7865cda67e34.png)

![image](https://user-images.githubusercontent.com/52652923/220855227-566903a4-42ad-4de9-8414-402171c4dcfe.png)

The [github status](https://www.githubstatus.com/history) page does show some issues around this time frame, but these were all solved:

![image](https://user-images.githubusercontent.com/52652923/220855851-9c8dac29-19c5-43ca-9835-06b043285087.png)

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

```
Current runner version: '2.301.1'
Operating System
  Microsoft Windows Server 2019
  10.0.17763
```

Private repo

### Is it regression?

Yes, sorry private repos

### Expected behavior

The build times should be fairly constant. 

### Actual behavior

Build times explode. Burning down our build minutes too fast.

### Repro steps

Compare build times on any windows environment from before Feb 18th with today.

**Comment by Tyrrrz** [comment]
I have observed this too. Example job: https://github.com/Tyrrrz/CliWrap/actions/runs/4271628026

- **Windows** – checkout takes **4m9s**:

![image](https://user-images.githubusercontent.com/1935960/222046611-680120d3-b5b3-4dd7-bc15-5f46ec8239ad.png)

- **Ubuntu** – checkout takes **<1s**:

![image](https://user-images.githubusercontent.com/1935960/222046665-029b86cc-968d-41cd-b0d8-711963d9cbd0.png)

- **macOS** – checkout takes **3s**:

![image](https://user-images.githubusercontent.com/1935960/222046745-531d4356-4130-4edb-9da8-76e5019e71da.png)

Note that this behavior is pretty inconsistent, and usually `checkout` completes pretty fast on Windows. But in the event that _it is_ slow, it's only ever slow on Windows.

**Comment by dscho** [comment]
I've encountered this and debugged it a bit, by heavily instrumenting the transpiled code in `dist/index.js`. Turns out that there are multiple calls to PowerShell that make a mess by essentially waiting for dozens of seconds. Here is the example run I analyzed:

- [here](https://github.com/dscho/git-for-windows-automation/actions/runs/4321187056/jobs/7546850451#step:2:363), 1 minute and 14 seconds are spent,
- [here](https://github.com/dscho/git-for-windows-automation/actions/runs/4321187056/jobs/7546850451#step:2:432), 11 seconds are spent,
- [here](https://github.com/dscho/git-for-windows-automation/actions/runs/4321187056/jobs/7546850451#step:2:447), 12 seconds are spent,
- [here](https://github.com/dscho/git-for-windows-automation/actions/runs/4321187056/jobs/7546850451#step:2:555), 11 seconds are spent,

all on [this PowerShell call](https://github.com/dscho/checkout/blob/a38d51372316a3bda6c90d22883a781513e803d1/dist/index.js#L2026-L2028):

```powershell
(Get-CimInstance -ClassName Win32_OperatingSystem).caption
```

totaling 1 minute and 48 whopping seconds just to determine a Windows release that the `actions/checkout` Action has no need to know.

To make things even worse, the same PowerShell invocation also happens multiple times during the post-action:

- [10 seconds here](https://github.com/dscho/git-for-windows-automation/actions/runs/4321187056/jobs/7546850451#step:4:292),
- [12 seconds there](https://github.com/dscho/git-for-windows-automation/actions/runs/4321187056/jobs/7546850451#step:4:361),
- [11 seconds there](https://github.com/dscho/git-for-windows-automation/actions/runs/4321187056/jobs/7546850451#step:4:376) and
- [12 seconds here](https://github.com/dscho/git-for-windows-automation/actions/runs/4321187056/jobs/7546850451#step:4:492)

I do not really understand what changed between Feb 17th and 21st that would explain this slowdown. There has not been a new `actions/checkout` release since Jan 5th...

**Comment by dscho** [comment]
I have briefly seen success trying to hard-code the fix of https://github.com/sindresorhus/windows-release/pull/18 into `dist/index.js` but it does not seem to work when I undelete all the core logic. *sigh*

At this point, I have to tend to other things, but I thought I'd leave my current findings here in case somebody else can take over (and try things like overriding `os.release()` to always return 2022 or something like that, _before_ letting `@octokit/endpoint` initialize its User-Agent string).

**Comment by BrettDong** [comment]
I made an attempt to avoid calling into `windows-releases` from the checkout action in #1246.

If you want to try you can use
```yaml
- uses: BrettDong/checkout@octokit
```
and see if there is any improvement in time stalled between starting the checkout action and performing actual git operations.

![image](https://user-images.githubusercontent.com/21075502/227773395-a93dfae7-0466-4a8a-a036-9e022eeb7af2.png)
![image](https://user-images.githubusercontent.com/21075502/227773425-51472e0e-6ba6-431c-bb7c-fd163e03994b.png)

**Comment by dscho** [comment]
@BrettDong excellent! I tested this and the times are back to decent levels: the _entire_ `checkout` step [takes 11 seconds with your PR](https://github.com/dscho/git-for-windows-automation/actions/runs/4526238192/jobs/7971269537). Thank you _so much_!

**Comment by BrettDong** [comment]
The fix in #1246 reduces stalled time down to 3 seconds.

![](https://user-images.githubusercontent.com/21075502/227791080-cd8e2ea4-3e6f-4b14-9013-7a991d4caed9.png)

During the 3 seconds the workflow is stalled on loading the `node.exe` from disk to memory for execution. I don't think there is anything I can do to get rid of it.

**Comment by Gakk** [comment]
I have had a similar issue with **large runners with slow checkout and cleanup** that I reported to GitHub Support. They concluded that it is related this issue, even though I am not completely convinced.

The screenshot from @Tyrrrz earlier in this issue also shows a slow post checkout (cleanup).

## Workflow:

To recreate as a minimum solution, I created a new repository with only a single workflow file, spinning up 3 jobs on default and large runners:

```
name: Demo Slow Checkout

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:

  doSomething:
  
    name: My Job

    strategy:
      matrix:
        os: [windows-latest, windows-latest-8core, windows-latest-16core]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
      # https://github.com/actions/checkout/releases
      with:
        # Fetch full depth
        fetch-depth: 0

    - name: Work for 15 seconds
      run: Start-Sleep -Seconds 15
```

In addition to checkout the job has only one other step, and that is to sleep for 15 seconds.

## Results:

The jobs executed 10 times, and shows that:

- **Checkout**
  - Normal time is 19 seconds
  - Large runners use **more than twice the time** _(between 47 and 51 seconds)_
- **Post Checkout**
  - Normal time is 3 seconds
  - Large runners use **15 times more time** _(between 46 and 49 seconds)_

![image](https://user-images.githubusercontent.com/5013909/227904623-1f74c18b-a465-4be9-ab8e-334ec302c0dc.png)
ℹ️ _The last row is median and not average, so that any single slow run should interfere with the result._

## Findings:

### Finding 1:
Every single checkout on the large runners is at least twice as slow as on regular runner, and all the times goes _before_ the actual checkout starts:
![image](https://user-images.githubusercontent.com/5013909/227904996-21e28a08-fd63-466f-9c36-d94d67e32a51.png)

### Finding 2:
The post checkout (cleanup) is on average **15 times slower** as on regular runner, and all the time also goes _before_ any cleanup is started:
![image](https://user-images.githubusercontent.com/5013909/227905016-b9378ef0-e017-43dd-bae4-6ddbc22894cb.png)

### Finding 3:
The simple sleep-task on regular runner uses twice the time of the sleep interval. How is it even possible that a sleep for 15 seconds takes almost double the time? This was done with a simple run: `Start-Sleep -Seconds 15`.
![image](https://user-images.githubusercontent.com/5013909/227905045-a8e0a834-8783-4df6-82a2-81e2ac3d0372.png)

**Comment by BrettDong** [comment]
You can build something like https://github.com/BrettDong/Cataclysm-DDA/blob/etw/.github/workflows/etw.yml to collect ETL traces in the runner to diagnose what is happening and spending time during `checkout`.

**Comment by ScottTodd** [comment]
> I have had a similar issue with **large runners with slow checkout and cleanup** that I reported to GitHub Support. They concluded that it is related this issue, even though I am not completely convinced.

Same here - we've noticed that large GitHub-managed Windows runners are substantially slower during checkout. This is not a recent regression for us though - they've been (nearly unuseably) slow for months.

| Runner | Checkout time |
|--------|--------|
| Self hosted Linux | 40s |
| small GitHub-managed windows (`windows-2022`) | 2m30s | 
| large GitHub-managed Windows | 12m |

We also have a ticket with GitHub Support, and I've been running experiments for our repo / workflows at https://github.com/openxla/iree/pull/12051.

**Comment by yeu-degroot** [comment]
Great news - build times on windows environment are back to normal!
This was fixed in [actions/checkout@3.5.1](https://github.com/actions/checkout/releases/tag/v3.5.1).

Thanks @BrettDong and @fhammerl

![image](https://user-images.githubusercontent.com/52652923/233103721-bf6c333e-8920-4c68-a027-6036a3333b1f.png)

**Comment by GMNGeoffrey** [comment]
FYI the issue that @ScottTodd and I are seeing on the large Windows managed runners was not fixed by this update. We tested it prior to release at the direction of GitHub support:

* yaml file (same location): https://github.com/ScottTodd/iree/blob/ci-windows-checkout-debug/.github/workflows/ci.yml
* logs: https://github.com/openxla/iree/actions/runs/4610834430

Seems like it may be a separate issue, but just wanted to call it out since these issues seem like they were maybe merged. Seems like this is also something that @Gakk is hitting. My understanding from support is that they're still investigating this other problem. It may be worth opening a separate issue for this or leaving this open.

**Comment by ofek** [comment]
https://github.com/actions/checkout/pull/1246#issuecomment-1499276093

**Comment by Gakk** [comment]
> Seems like this is also something that @Gakk is hitting.

@GMNGeoffrey, I have done extensive testing and confirmed that my issues were resolved by actions/checkout version 3.5.1.

**Comment by ScottTodd** [comment]
Yep, I'm still seeing substantially slower checkouts on large runners (could break that out into a different issue, and we have a support ticket for it). Latest experiments on https://github.com/openxla/iree/pull/12051, logs at https://github.com/openxla/iree/actions/runs/4748455722/jobs/8434667258. Our repo depends on https://github.com/llvm/llvm-project/ (very large) and a few other submodules, and just the checkout takes ~1 minute on small Windows runners but 7+ minutes on large Windows runners. We've tried all sorts of ways to change the git commands used (sparse checkouts, shallow clones, caching of git files, etc.) but can't get past whatever the differences are between the runners themselves.

**Comment by ofek** [comment]
As mentioned in a comment above, can you try this? https://github.com/BrettDong/Cataclysm-DDA/blob/etw/.github/workflows/etw.yml

I don't have access to larger runners currently to test myself.

**Comment by dscho** [comment]
> I'm still seeing substantially slower checkouts on large runners

Just a wild guess: could it be that large runners have slower D: drives than smaller runners? IIRC the hosted runners specifically have _very_ fast D: drives.

**Comment by GMNGeoffrey** [comment]
I've just verified that the issue is not with the runners themselves, but rather with actions/checkout. Using just the normal bash commands, I did full checkout with submodules in 1m30s, compared to almost 10m previously. By dropping `actions/checkout` and `actions/cache` and rolling our own pretty unsophisticated solutions, I've been able to drop a maximally cached build from [20m](https://github.com/openxla/iree/actions/runs/4748717136/jobs/8435229260) (and that's when fetching the cache doesn't just fail entirely) to [9m](https://github.com/openxla/iree/actions/runs/4750681034/jobs/8439091687). That is just really pretty sad

**Comment by BrettDong** [comment]
You can collect ETW traces to help diagnose what's happening and taking time during checkout action.

**Comment by GMNGeoffrey** [comment]
> You can collect ETW traces to help diagnose what's happening and taking time during checkout action.

> As mentioned in a comment above, can you try this? https://github.com/BrettDong/Cataclysm-DDA/blob/etw/.github/workflows/etw.yml
> 
> I don't have access to larger runners currently to test myself.

Yeah, but presumably so can the GitHub engineers who support says are working to fix this. Like, IDK, it kind of seems to me that the people who wrote this code, control these VMs, and whom we are paying for this service, could maybe take a look at the issues with it.

**Comment by dscho** [comment]
@GMNGeoffrey I would like to encourage you to consider the current macro-economical climate, and also just [how large he roadmap is](https://github.com/orgs/github/projects/4247/views/1). And please also note how @BrettDong's effort was rewarded: I am sure that you also will get what you want much quicker if you dig a little deeper with those ETW traces. I would even consider to help, but I do not have access to those large runners; You do, though.

**Comment by nebuk89** [comment]
👋 hey sorry for not seeing this one, we are tracking/providing commentary on our investigation on the windows larger runner checkout here: https://github.com/github/c2c-actions-support/issues/2002 

We are also tracking this issue as well as part of this :( sorry for missing the thread.

**Comment by GMNGeoffrey** [comment]
Thanks Ben. Further runs suggest that my switch to use git commands directly instead of actions/checkout was just lucky the first few times (or the computer learned what I was trying to do and put a stop to it :stuck_out_tongue:). Subsequent runs have had similar latency to before the switch, I think (I started hacking together a script to collect statistics for jobs over time, but got side-tracked, so pure anecdata right now). So I'm back to thinking it's the VM+git itself and not the action. I am sort of considering getting tarballs for all of the submodules instead of using git... I'll update if that seems to be faster somehow (which would suggest to me something git-specific and not just IO or network issues)

**Comment by nebuk89** [comment]
Thanks @GMNGeoffrey for having a go! (and sorry that the computers are learning 😆 ) Let me know if it's faster and we will hopefully have our focus back on this in the next week or so as things settle (also turns out I am not a maintainer on this repo, I will find someone to re-open this for me :D)

**Comment by myitcv** [comment]
Just a reminder, given the evidence in https://github.com/actions/runner-images/issues/7320, there is almost certainly an underlying issue that is not specific to `git` at all. Rather, all operations that place high demands on disk (and CPU).

**Comment by benwells** [comment]
Re-opening at @nebuk89's request, so we can track our efforts externally as we investigate further.  Some valuable context built up in this thread 😄 .

**Comment by Plasma** [comment]
I'm not using these runners, but if the OS is showing high CPU on disk access, perhaps its due to a Host Disk Caching setting set by Azure on the VM Disk (see https://learn.microsoft.com/en-us/azure/virtual-machines/disks-performance) as while the Host Disk cache benefits for some modes, it can also add a penalty.

**Comment by StephanKirsch** [comment]
Not sure if it helps - since we are running self-hosted gitlab, but I started looking for solution since our Windows runners are incredibly slow. Simple build jobs (for instance just perform MSBuild on a solution) that finish in less than 1 minute when run manually on the same machine - take over an hour when run as gitlab-runner job. The very same script is executed, no manual deviation in the two procedures. Further potentially helpful details:

- We have runners on virtual machines and on physical ones - makes no difference, both are concerned
- Runners use Windows 10
- There is no load to be seen, not on CPU, nor memory, nor disk, just all silent and idle
- I so far failed to pinpoint the delays to any step. E. g. simply the output of MSBuild is tremendously slowed down. Lines that pass within fractions of a second normally drop in every other minute only

**Comment by Plasma** [comment]
It almost sounds like the runner is maybe slow / blocking reading stderr/out of the console windows of the processes it’s launched, which is blocking the process advancing.

**Comment by stellaraccident** [comment]
We are discontinuing our use of GH managed windows runners. The costs were already beyond premium/sustainable, and the performance is so poor that the issue compounds out of control. I don't consider this a viable way to run CI for any business.

I can tolerate a lot but not at massively inflated prices.
