### ISSUE TITLE
Failed to download action 'https://api.github.com/repos/actions/checkout/tarball/ee0669bd1cc54295c223e0bb666b733df41de1c5'. Error: Response status code does not indicate success: 503 (Service Unavailable)

### ISSUE THREAD

**Issue by copyNdpaste** [actions/checkout#1457]
v3, v2 not work
```
Current runner version: '2.308.0'
Runner name: 'ecs-ec-backend-runner-dev'
Runner group name: 'Default'

GITHUB_TOKEN Permissions
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v2' ()
Warning: Failed to download action 'https://api.github.com/repos/actions/checkout/tarball/ee0669bd1cc54295c223e0bb666b733df41de1c5'. Error: Response status code does not indicate success: 503 (Service Unavailable).
```

**Comment by leepowellnbs** [comment]
Getting the same on `actions/checkout@v3`

**Comment by copyNdpaste** [comment]
action works now.....

**Comment by RMEngels** [comment]
Seems to be unrelated to version, v4 also fails here

**Comment by Lyokolux** [comment]
It seems to fail from time to time. As the checkout didn't change and it works partially, maybe something is going on by Github.

**Comment by thboop** [comment]
Hey folks, we are aware of this issue. The incident should be resolved now but please let us know if you see it again.

**Comment by slavik-pastushenko** [comment]
> Hey folks, we are aware of this issue. The incident should be resolved now but please let us know if you see it again.

@thboop Hey Thomas! Seems like an issue is still in place, for both v3 & v4.

**Comment by tepatelcmc** [comment]
Hi
I am still experiencing this issue and it seems to be a blocker. Any other workaround?
