### ISSUE TITLE
Checkout fails on windows-latest when using @master

### ISSUE THREAD

**Issue by arlyon** [actions/checkout#84]
Builds are failing on windows. Logs attached.

```
2019-12-03T16:15:23.3178351Z ##[section]Starting: Request a runner to run this job
2019-12-03T16:15:24.2697462Z Requesting a hosted runner in current repository's account/organization with labels: 'windows-latest', require runner match: True
2019-12-03T16:15:24.3347571Z Labels matched hosted runners has been found, waiting for one of them get assigned for this job.
2019-12-03T16:15:24.3834888Z ##[section]Finishing: Request a runner to run this job
2019-12-03T16:15:31.7862022Z Current runner version: '2.161.0'
2019-12-03T16:15:31.7863222Z Prepare workflow directory
2019-12-03T16:15:31.8356961Z Prepare all required actions
2019-12-03T16:15:31.8391209Z Download action repository 'actions/checkout@master'
2019-12-03T16:15:32.7930286Z Download action repository 'actions/setup-python@master'
2019-12-03T16:15:33.7783103Z Download action repository 'actions/upload-artifact@master'
2019-12-03T16:15:34.1439691Z ##[group]Run actions/checkout@master
2019-12-03T16:15:34.1440081Z with:
2019-12-03T16:15:34.1440360Z   repository: arlyon/graphics
2019-12-03T16:15:34.1440572Z   token: ***
2019-12-03T16:15:34.1440704Z   clean: true
2019-12-03T16:15:34.1440818Z   fetch-depth: 1
2019-12-03T16:15:34.1440948Z   lfs: false
2019-12-03T16:15:34.1441076Z ##[endgroup]
2019-12-03T16:15:35.1466185Z Added matchers: 'checkout-git'. Problem matchers scan action output for known warning or error strings and report these inline.
2019-12-03T16:15:35.1467998Z Syncing repository: arlyon/graphics
2019-12-03T16:15:35.1468618Z Working directory is 'd:\a\graphics\graphics'
2019-12-03T16:15:35.1568360Z [command]"C:\Program Files\Git\bin\git.exe" version
2019-12-03T16:15:35.1768829Z git version 2.23.0.windows.1
2019-12-03T16:15:35.2022792Z Removed matchers: 'checkout-git'
2019-12-03T16:15:35.2024723Z ##[error]Command failed: rd /s /q "d:\a\graphics\graphics"
The process cannot access the file because it is being used by another process.

2019-12-03T16:15:35.2106752Z ##[error]Node run failed with exit code 1
2019-12-03T16:15:35.2147889Z Cleaning up orphan processes
```

Changing the version to @v1 seems to resolve the problem.

**Comment by gh-davidc** [comment]
Same thing here, also I've seen that even your Github Actions failed in your last commit https://github.com/actions/checkout/compare/v2-beta...master

I'm downgrading to v1, thanks @arlyon !

**Comment by runspired** [comment]
Seems to be broken in all OS's

**Comment by ericsciple** [comment]
@arlyon thanks! fixed now. i'll push the tag forward

**Comment by arlyon** [comment]
Thanks for the quick fix :)

**Comment by dlemstra** [comment]
We are still experiencing this issue and it looks like it is related to the fact that we specify `ref: refs/heads/master` in our build (https://github.com/ImageMagick/ImageMagick/blob/53ba89cc416c2f1255197f85d1a17c85a0c06760/.github/workflows/daily.yml#L79). Should I open a new issue for this or is it related to this one? The build log can be found here: https://github.com/ImageMagick/ImageMagick/runs/334366719

**Comment by ericsciple** [comment]
@dlemstra it looks like you specify `remotes/origin/master` as the ref. `refs/heads/master` or `master` should work.

It looks like a different bug than the one this issue was tracking. I think it should be a new issue.

**Comment by ericsciple** [comment]
@dlemstra note, for a quick mitigation you can also pin back to `actions/checkout@v1`. I'm still interested in this bug though, it's a ref format i hadnt considered (v2 contains more narrow refspec during fetch in order to achieve perf improvements).

**Comment by ericsciple** [comment]
@dlemstra fyi I opened https://github.com/actions/checkout/issues/98 to track the issue you described
