### ISSUE TITLE
Deprecation Warning Output from GitHub Actions

### ISSUE THREAD

**Issue by mcichoski** [actions/checkout#959]
## Behaviour

Warning: `The 'save-state' command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/`

Warning: `The 'set-output' command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/`

As per [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](url)

### Steps to reproduce this Issue
1. use `actions/checkout@v3`  to checkout a repository

**Comment by ustc-comb** [comment]
> ## Behaviour
> Warning: `The 'save-state' command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/`
> 
> Warning: `The 'set-output' command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/`
> 
> As per [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](url)
> 
> ### Steps to reproduce this Issue
> 1. use `actions/checkout@v3`  to checkout a repository

I'm using github pages. The `github-pages[bot]` use `actions/checkout@v2` automatically, I don't know how to change that.

**Comment by rentziass** [comment]
Hi @cyhcyh, this is expected as we're beginning to deprecate those workflow and started updating actions with a fix. We're back-porting that fix to checkout@v2 shortly to solve this for people that don't have control over the version of checkout that is being used, I'll report here as soon as that's done!

**Comment by cyhcyh** [comment]
> Hi @cyhcyh, this is expected as we're beginning to deprecate those workflow and started updating actions with a fix. We're back-porting that fix to checkout@v2 shortly to solve this for people that don't have control over the version of checkout that is being used, I'll report here as soon as that's done!

That's great! Thank you!

**Comment by rentziass** [comment]
`checkout@v2` is now pointing to [`v2.5.0`](https://github.com/actions/checkout/releases/tag/v2.5.0) and warnings about workflow commands being deprecated should not happen anymore 🎉  Please do let me know if that is not the case!

**Comment by davetapley** [comment]
@rentziass still seeing this:

```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/checkout, actions/upload-artifact, actions/checkout, actions/checkout
```

I even tried being explicit with `uses: actions/checkout@v2.5.0`, but seeing the same. Any ideas? 🤔

**Comment by TWiStErRob** [comment]
@davetapley you need to use 3+ for that: https://github.com/actions/checkout/releases/tag/v3.0.0

2.5.0 was just a maintenance release for those who are still on v2 as far as I understand it.

**Comment by TWiStErRob** [comment]
As I understand this is now fixed for both
 * v2 https://github.com/actions/checkout/pull/962 (released [2.5.0](https://github.com/actions/checkout/releases/tag/v2.5.0))
 * v3 https://github.com/actions/checkout/pull/939 (released [3.1.0](https://github.com/actions/checkout/releases/tag/v3.1.0))

@rentziass close as completed?

**Comment by rentziass** [comment]
That's correct, thanks for the help @TWiStErRob! Closing now.

**Comment by theofficialgman** [comment]
@rentziass I'm still getting this warning from action/checkout v2.5.0

**Comment by TWiStErRob** [comment]
@theofficialgman I think you're better off creating a new issue with detail (screenshot, link, yml, logs).

**Comment by jespertheend** [comment]
I can confirm v2.5.0 still seems to trigger the deprecation warning. Upgrading to v3.1.0 fixed it for me though.

**Comment by annaesvensson** [comment]
I am seeing the same issue in our repository. With `checkout@v2` the [deprecation warnings are there](https://github.com/datenstrom/yellow/actions/runs/3446741108), after switching to `checkout@v3` the [warnings are gone](https://github.com/datenstrom/yellow/actions/runs/3461372275). Upgrading to v3 fixed it for us.

**Comment by MikeMcC399** [comment]
@davetapley 

There are two different deprecation warning messages.

The original one from this issue was about `save-state` and `set-output` which @rentziass wrote is fixed for `actions/checkout@v2` and `actions/checkout@v3`.

The other deprecation warning message "Node.js 12 actions are deprecated." mentioned by @davetapley is not fixed in `actions/checkout@v2`.

`actions/checkout@v2` runs under `node12` as can be seen by https://github.com/actions/checkout/blob/e2f20e631ae6d7dd3b768f56a5d2af784dd54791/action.yml#L74-L77 pointed to by https://github.com/actions/checkout/tree/v2

So, if you want to stop the "Node.js 12 actions are deprecated." warning from appearing, you need to update to `actions/checkout@v3`. @annaesvensson already wrote about this. The above is just an explanation for it.

**Comment by tal-lederman-dy** [comment]
I'm using `actions/checkout@v3.3.0`, but still getting the same warning:
`Warning: The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/`

**Comment by MikeMcC399** [comment]
@tal-lederman-dy 

> I'm using actions/checkout@v3.3.0, but still getting the same warning

Since this issue was already resolved in `actions/checkout@v3` it is mostly likely that your problem has another origin. This could be from a step in the workflow or from calling another GitHub action.

I suggest to re-run your action with `ACTIONS_STEP__DEBUG` set `true` (see https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging) to get a better idea about where the warning might be coming from.

Here is an example log output from using an older version of another action:

```text
::set-output name=dashboardUrl::
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/``
```
